[files]
recent_files=/home/craftworkson/Desktop/make-all-horoscopes;/home/craftworkson/Documents/NewProject/Source/PluginEditor.cpp;/home/craftworkson/main.cpp;/home/craftworkson/Desktop/juce_sample_j/NewProject/JuceLibraryCode/modules/juce_dsp/juce_dsp.cpp;/home/craftworkson/Desktop/juce_sample_j/NewProject/JuceLibraryCode/modules/juce_dsp/filter_design/juce_FilterDesign.cpp;/home/craftworkson/Desktop/juce_sample_j/NewProject/JuceLibraryCode/modules/juce_dsp/processors/juce_Oversampling.h;/home/craftworkson/Desktop/Projects/walk.py;/home/craftworkson/Desktop/.~lock.FOOD-COSTING_GINGER-HOUSE_2025.osd.ods#;/home/craftworkson/.local/share/applications/bCNC.desktop;/home/craftworkson/Desktop/clmystery/mystery/crimescene;
recent_projects=
current_page=2
FILE_NAME_0=0;Python;0;EUTF-8;1;1;0;%2Fhome%2Fcraftworkson%2FDesktop%2FBooks%2FElettronica%2Fsemplify.py;0;4
FILE_NAME_1=0;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fcraftworkson%2F.local%2Fshare%2Fapplications%2FbCNC.desktop;0;4
FILE_NAME_2=0;Python;0;EUTF-8;1;1;0;%2Fhome%2Fcraftworkson%2FDesktop%2Fmake-all-horoscopes;0;4

[project]
session_file=
project_file_path=/home/craftworkson/projects

[geany]
treeview_position=225
msgwindow_position=253
geometry=840;20;836;485;0;
sidebar_page=1

[VTE]
last_dir=/home/craftworkson

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=546
position_find_y=455
position_replace_x=-1
position_replace_y=-1
position_fif_x=517
position_fif_y=398

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
