--disable-gpu-compositing
--enable-smooth-scrolling
--enable-pinch
--touch-events=enabled
--enable-gpu-rasterization
--num-raster-threads=4
--enable-zero-copy
--enable-native-gpu-memory-buffers
--disable-threaded-scrolling=false
--enable-composited-scrolling

