# SPDX-License-Identifier: GPL-3.0-or-later
# DevOS ships the linux-lts kernel, so the initcpio module must build the
# linux-lts preset. Without this override Calamares uses its stock default
# (kernel: linux) and runs `mkinitcpio -p linux`, which fails on the target —
# there is no /etc/mkinitcpio.d/linux.preset, only linux-lts.preset.
# Equivalent to install.sh's `mkinitcpio -P` given DevOS's single kernel.
---
kernel: linux-lts
be_unsafe: false
