# SPDX-License-Identifier: GPL-3.0-or-later
# initcpiocfg writes the target's /etc/mkinitcpio.conf. DevOS keeps it at
# defaults: the installed-system HOOKS come from the devossetup module's
# /etc/mkinitcpio.conf.d/devos.conf drop-in (which overrides the main conf),
# and the kernel preset is set in initcpio.conf. initcpiocfg has NO 'kernel'
# key — the old `kernel: linux-lts` here was a misplaced no-op (the reason
# mkinitcpio defaulted to the wrong preset).
---
useSystemdHook: false
