efiSystemPartition:       "/boot"
efiSystemPartitionSize:   "512MiB"
efiSystemPartitionName:   "EFI"
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions:     false
alwaysShowPartitionLabels: true
defaultFileSystemType:    "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]

initialPartitioningChoice: erase
initialSwapChoice:         none
