userShell:          /usr/bin/zsh

defaultGroups:
    - name: wheel
      must_exist: false
      system: true
    - name: audio
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: input
      must_exist: false
      system: true
    - name: render
      must_exist: false
      system: true

autologinGroup:     autologin
doAutologin:        false
sudoersGroup:       wheel
setRootPassword:    false
doReusePassword:    true
passwordRequirements:
    minLength: 6
    maxLength: -1
    libpwquality:
        - minlen=6

avatarFilePath:     .face
permitWeakPasswords: false
