showSupportUrl:        true
showKnownIssuesUrl:    true
showReleaseNotesUrl:   false
showDonateUrl:         false

requirements:
    checker: default
    required:
        - storage
        - ram
        - power
        - internet
    mandatory:
        - storage
        - ram
        - internet
    storageGB:    20
    ramGB:        2
    internetURL:  https://archlinux.org
