#Section "InputClass"
#        Identifier "system-keyboard"
#        MatchIsKeyboard "on"
#        Option "XkbLayout" "us"
#EndSection



#Section "InputClass"
#    Identifier "Apple Internal Keyboard"
#    MatchProduct "Apple Internal Keyboard"
#    Option "AutoEnable" "true"
#EndSection


#Section "InputClass"
#    Identifier "bcm5974"
#    MatchDriver "bcm5974"
#    Option "AccelerationProfile" "-1"
#    Option "DisableWhileTyping" "1"
#EndSection

Section "InputClass"
    Identifier "Enable tap-to-click for bcm5974"
    MatchProduct "bcm5974"
    MatchIsTouchpad "on"
    Driver "libinput"

    Option "Tapping" "on"                     # Tap to click
    Option "NaturalScrolling" "true"          # Optional: Natural scroll direction
    Option "DisableWhileTyping" "true"        # Prevent accidental touches while typing
    Option "TappingDrag" "true"               # Allow tap-dragging
    Option "ClickMethod" "clickfinger"        # One, two, three-finger click
    Option "AccelProfile" "adaptive"          # Adaptive acceleration
EndSection
