Section "InputClass"
    Identifier "Apple Magic Mouse 2"
    MatchProduct "Apple Magic Mouse 2"
    Driver "libinput"
    Option "ScrollMethod" "twofinger"
    Option "NaturalScrolling" "true"
EndSection
